export const engineConfig = {
  engine: {
    engineType: "V",
    cylinderCount: 16,
    minRPM: 800,
    maxRPM: 8000,
    idleRPM: 820,
    // Higher smoothness dampens pulse roughness and random flutter.
    smoothnessFactor: 0.88,
    idleJitterAmount: 0.01,
    idleJitterWindowRPM: 350,
    limiter: {
      enterRPMOffset: 140,
      exitRPMOffset: 300,
      holdSeconds: 0.08,
      clampRPMOffset: 90,
    },
  },
  smoothing: {
    rpmSeconds: 0.08,
    throttleSeconds: 0.055,
    loadSeconds: 0.095,
    cameraSeconds: 0.15,
    distanceSeconds: 0.2,
  },
  buses: {
    interior: {
      masterGain: 1,
      lowPassHz: 1800,
      lowPassHzAtLoad0: 1400,
      lowPassHzAtLoad1: 2850,
      mechanicalPresenceDb: 2.5,
    },
    exterior: {
      masterGain: 1,
      highPassHz: 60,
      brightnessDb: 3,
      brightnessDbAtLoad0: 1,
      brightnessDbAtLoad1: 5.5,
    },
    distance: {
      minAttenuation: 0.45,
    },
  },
  events: {
    engineStart: {
      clip: null,
      gain: 0.55,
    },
    engineStop: {
      clip: null,
      gain: 0.45,
    },
    shiftThunk: {
      clip: null,
      gain: 0.52,
      torqueDip: 0.55,
      torqueDipSeconds: 0.16,
    },
    limiterStutter: {
      clip: null,
      gain: 0.24,
      repeatSeconds: 0.065,
      cutRateHz: 24,
      cutDutyCycle: 0.34,
      cutMinGain: 0.42,
    },
    throttleBlip: {
      clip: null,
      gain: 0.24,
      minRPM: 1200,
      maxRPM: 4800,
      minThrottleJump: 0.35,
      minGapSeconds: 0.2,
    },
    backfire: {
      clip: null,
      gain: 0.42,
      minRPM: 4200,
      minGapSeconds: 0.24,
    },
  },
  // Example V16 setup tuned for smooth, dense, exotic tone.
  layers: [
    {
      name: "exhaust",
      baseGain: 0.84,
      interiorSend: 0.45,
      exteriorSend: 1,
      transitionSeconds: 0.032,
      powerPresence: 1.08,
      coastPresence: 0.9,
      lowLoadGain: 0.9,
      highLoadGain: 1.12,
      brightnessDbAtLoad0: -2.2,
      brightnessDbAtLoad1: 4.5,
      microPitchFlutter: 0.0025,
      microGainFlutter: 0.009,
      pulseDepth: 0.03,
      pulseRateDivisor: 4,
      pulseHarmonicMix: 0.35,
      highEndHarmonicGain: 1.4,
      bands: [
        {
          name: "idle",
          recordedRPM: 820,
          clip: null,
          powerClip: null,
          coastClip: null,
          gain: 1,
        },
        {
          name: "low",
          recordedRPM: 2000,
          clip: null,
          powerClip: null,
          coastClip: null,
          gain: 1,
        },
        {
          name: "mid",
          recordedRPM: 4200,
          clip: null,
          powerClip: null,
          coastClip: null,
          gain: 1,
        },
        {
          name: "high",
          recordedRPM: 7000,
          clip: null,
          powerClip: null,
          coastClip: null,
          gain: 1,
        },
      ],
    },
    {
      name: "intake",
      baseGain: 0.74,
      interiorSend: 0.86,
      exteriorSend: 0.7,
      transitionSeconds: 0.03,
      powerPresence: 1.1,
      coastPresence: 0.74,
      lowLoadGain: 0.8,
      highLoadGain: 1.08,
      brightnessDbAtLoad0: -3.2,
      brightnessDbAtLoad1: 4.8,
      microPitchFlutter: 0.002,
      microGainFlutter: 0.008,
      pulseDepth: 0.022,
      pulseRateDivisor: 4,
      pulseHarmonicMix: 0.4,
      highEndHarmonicGain: 1.8,
      bands: [
        { name: "idle", recordedRPM: 820, clip: null, powerClip: null, coastClip: null, gain: 1 },
        { name: "low", recordedRPM: 2000, clip: null, powerClip: null, coastClip: null, gain: 1 },
        { name: "mid", recordedRPM: 4200, clip: null, powerClip: null, coastClip: null, gain: 1 },
        { name: "high", recordedRPM: 7000, clip: null, powerClip: null, coastClip: null, gain: 1 },
      ],
    },
    {
      name: "mechanical",
      baseGain: 0.6,
      interiorSend: 1.14,
      exteriorSend: 0.6,
      transitionSeconds: 0.028,
      powerPresence: 0.92,
      coastPresence: 1.02,
      lowLoadGain: 0.92,
      highLoadGain: 1.06,
      brightnessDbAtLoad0: -1.8,
      brightnessDbAtLoad1: 3.6,
      microPitchFlutter: 0.0018,
      microGainFlutter: 0.007,
      pulseDepth: 0.018,
      pulseRateDivisor: 3,
      pulseHarmonicMix: 0.5,
      highEndHarmonicGain: 2.2,
      bands: [
        { name: "idle", recordedRPM: 820, clip: null, powerClip: null, coastClip: null, gain: 1 },
        { name: "low", recordedRPM: 2000, clip: null, powerClip: null, coastClip: null, gain: 1 },
        { name: "mid", recordedRPM: 4200, clip: null, powerClip: null, coastClip: null, gain: 1 },
        { name: "high", recordedRPM: 7000, clip: null, powerClip: null, coastClip: null, gain: 1 },
      ],
    },
  ],
};
